# Generated by Django 5.1.2 on 2024-10-24 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishes',
            name='category',
            field=models.CharField(choices=[('starter', 'Starter'), ('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner')], default='starter', max_length=10),
        ),
    ]
