# Generated by Django 5.1.2 on 2024-10-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_reservation_first_name_reservation_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='number_of_people',
            field=models.IntegerField(default=1),
        ),
    ]
