# Generated by Django 5.1.2 on 2024-11-23 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_dishes_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishes',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
