# Generated by Django 5.1.2 on 2024-11-23 23:08

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_dishes_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishes',
            name='image',
            field=cloudinary.models.CloudinaryField(default=2, max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
