# Generated by Django 5.1.2 on 2024-11-23 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_dishes_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishes',
            name='image',
            field=models.URLField(max_length=500),
        ),
    ]
